# https://bioconda.github.io/recipes/spliceai/README.html
FROM quay.io/biocontainers/spliceai:1.3.1--py_0

RUN curl https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta  -o Homo_sapiens_assembly19.fasta
RUN curl https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.fai  -o Homo_sapiens_assembly19.fasta.fai

